import { useState } from "react";
import { Accessibility, Boxes, Database, Gauge, Layers3, Route, Zap } from "lucide-react";
import { Badge } from "@workspace/portfolio-design-system/components/ui/badge";
import { Card, CardContent } from "@workspace/portfolio-design-system/components/ui/card";
const principles = [
  ["Route splitting", "Only ship the surface the user asked for.", Route, "The /work and /architecture modules are lazy boundaries. The first view stays small; intent pulls in the rest."],
  ["Shared tokens", "One language, many surfaces.", Layers3, "The portfolio consumes the shared package directly. Color, type, radius, and primitives do not fork at the edge."],
  ["Micro frontends", "Ownership without visual drift.", Boxes, "Each feature can own its route module, loading behavior, and failure boundary while remaining composed in a common shell."],
  ["Caching", "Keep useful work useful.", Database, "Stable application boundaries make caching and measured invalidation possible instead of accidental."],
  ["Performance", "Measure before you polish.", Gauge, "A fast initial surface, deliberate motion, and less critical-path JavaScript are features, not implementation trivia."],
  ["Accessibility", "The interface includes everyone.", Accessibility, "Semantic HTML, focus-visible states, reduced motion, and keyboard-first interactions are part of the architecture."],
];
export default function Architecture() { const [active, setActive] = useState(0); const [reduced, setReduced] = useState(false); const [ItemIcon] = [principles[active][2]]; return <div className="mx-auto max-w-7xl px-5 py-16 md:px-10 md:py-24">
  <div className="max-w-4xl"><p className="eyebrow">Interactive architecture lab</p><h1 className="page-title">Make the invisible<br /><span className="accent-text">load-bearing.</span></h1><p className="lede">A small, tangible model of the decisions behind production frontend work. Select a principle. Inspect the boundary. Notice what it protects.</p></div>
  <div className="mt-14 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><div className="space-y-2">{principles.map(([title, tagline, Icon], i) => <button type="button" key={title} onClick={() => setActive(i)} className={`principle-button ${active === i ? "principle-active" : ""}`} data-testid={`button-principle-${i}`}><span className="flex items-center gap-3"><Icon size={18} /><span className="text-left"><strong className="block">{title}</strong><small>{tagline}</small></span></span><span className="font-mono text-xs">0{i + 1}</span></button>)}</div>
    <Card className="lab-panel"><CardContent className="p-7 md:p-10"><div className="flex items-start justify-between"><Badge>BOUNDARY 0{active + 1}</Badge><ItemIcon className="text-primary" size={28} /></div><h2 className="mt-10 text-3xl font-semibold">{principles[active][0]}</h2><p className="mt-2 text-lg text-muted-foreground">{principles[active][1]}</p><div className="lab-diagram my-10"><span className="diagram-node">SHELL</span><span className="diagram-line" /><span className="diagram-node diagram-node-active">{principles[active][0].toUpperCase()}</span><span className="diagram-line" /><span className="diagram-node">USER</span></div><p className="max-w-xl leading-relaxed text-muted-foreground">{principles[active][3]}</p><button type="button" className="mt-8 flex items-center gap-2 text-sm text-primary underline-offset-4 hover:underline" onClick={() => setReduced(!reduced)} data-testid="button-motion-toggle"><Zap size={15} /> {reduced ? "Motion preference: reduced" : "Motion preference: considered"}</button></CardContent></Card></div>
  <div className="mt-20 grid gap-5 md:grid-cols-3"><Card><CardContent className="p-6"><p className="font-mono text-xs text-primary">CONTRACT</p><p className="mt-4 text-lg font-medium">Every feature owns its failure state.</p></CardContent></Card><Card><CardContent className="p-6"><p className="font-mono text-xs text-primary">COMPOSITION</p><p className="mt-4 text-lg font-medium">Shared primitives prevent accidental drift.</p></CardContent></Card><Card><CardContent className="p-6"><p className="font-mono text-xs text-primary">OBSERVABILITY</p><p className="mt-4 text-lg font-medium">Performance is a behavior to inspect.</p></CardContent></Card></div>
</div>; }